### ISSUE TITLE
sessions_in_range for LEAPS returning incorrect number

### ISSUE THREAD

**Issue by pchaganti** [gerrymanoim/exchange_calendars#14]
Trying to get trading sessions for long term options. Always returns 255 even though it is definitely much more than that. Am I not using the library correctly?

```python
xnys = ecals.get_calendar("XCBF")

trading_days = xnys.sessions_in_range(pd.Timestamp("2021-03-11", tz=pytz.UTC), pd.Timestamp("2023-01-20", tz=pytz.UTC))

print(len(trading_days))

255
```

thanks!

**Comment by gerrymanoim** [comment]
@pchaganti - apologies for the very late reply - I somehow missed this issue. 

This is because of end_default here: https://github.com/gerrymanoim/exchange_calendars/blob/master/exchange_calendars/exchange_calendar.py#L40. 

You can manually create a calendar with any end date via the actual calendar class. 

A long time ago I started fixing this in https://github.com/quantopian/trading_calendars/pull/176/files (so you could pass whatever end date you wanted to `get_calendar`) but it was never merged because it might have caused incompatibilities with `zipline`. We don't need to strictly do that anymore so a similar approach should now we possible.
