### ISSUE TITLE
last_session & last_session_close return 2023 year timestamps

### ISSUE THREAD

**Issue by jangminhyeok** [gerrymanoim/exchange_calendars#155]
I tested in my pc and colaboratory.
I followed below process.

--------------
!pip install exchange_calendars
import exchange_calendars as ecals
import pandas as pd

xkrx = ecals.get_calendar("XKRX")
xkrx.last_session_close

--------------
it returns "Timestamp('2023-03-03 06:30:00')"
it also happens in other markets.

**Comment by maread99** [comment]
@jangminhyeok, the behaviour you're describing is the expected behaviour. These properties refer to the session at the right end of the calendar. Together with the `first_session` and `first_session_open` they describe the calendar bounds.

If you were after the 'current' session there's not a direct method that I'm aware of, although `xkrx.minute_to_session(pd.Timestamp.now())` should do the job.

**Comment by jangminhyeok** [comment]
@maread99 Thank you for the advice. My intention was to find the most recent day of the stock exchange opened as of today. So, as you said, I tried to find a function to search based on minute and coded it as follows. The problem has been solved and I will close the thread. Thank you.

------------
xkrx.previous_close(pd.Timestamp.now(tz='UTC').strftime('%Y-%m-%d %H:%M')).tz_convert(xkrx.tz).strftime('%Y%m%d')
------------

**Comment by maread99** [comment]
`session = xkrx.minute_to_session(pd.Timestamp.now(), direction="previous")`

or if you always want the previous session (as opposed to the current session if the market is open):

`session = xkrx.minute_to_past_session(pd.Timestamp.now(), 1)`

Check out the docstrings for what these methods are doing.
