### ISSUE TITLE
President Bush Funeral is missing from NYSE adhock calendar

### ISSUE THREAD

**Issue by yarimiz** [gerrymanoim/exchange_calendars#170]
On 05/12/2018 the US stock market had been closed due to the President Bush Funeral. This is missing from the adhoc calendar.

**Comment by maread99** [comment]
Hi @yarimiz, thanks for the advices.

All calendar updates rely on user contributions. You can click through to the workflow from [this FAQ](https://github.com/gerrymanoim/exchange_calendars#calendar-is-missing-a-holiday-has-a-wrong-time-should-have-a-break-etc).

I'll leave the issue open so that, if you're not able to PR it, somebody else might pick up on it at a later date.

**Comment by mixilchenko** [comment]
Hi, @yarimiz 
Can't find any announcements about it. Could you please provide a link

**Comment by herebebeasties** [comment]
@mixilchenko This was well-documented at the time: https://www.google.com/search?q=bush+funeral+markets

This was added two days before the funeral happened, to the USNationalDaysofMourning list, which itself is in the AdHoc list: https://github.com/gerrymanoim/exchange_calendars/commit/4f7cf8f6c145869d1e29b76d3b18cdea72ffe4ad

This shipped in v0.21 as you can see from the release notes: https://pandas-market-calendars.readthedocs.io/en/latest/change_log.html#id29

Looks like this should be closed to me, unless @yarimiz would like to be more specific around what he thinks is wrong here?
