### ISSUE TITLE
v4 Versioneer error

### ISSUE THREAD

**Issue by mixilchenko** [gerrymanoim/exchange_calendars#205]
Hi,
versioneer info is broken in v4.0.1 release

Getting with locally installed code
```python
>>> import exchange_calendars
>>> exchange_calendars._version.get_versions()
{'version': '4.0.1', 'full-revisionid': '687f0657b6bb27bbe2c59f3aec1e50fe5ce60925', 'dirty': False, 'error': None, 'date': '2022-06-22T13:08:25+0100'}
```

Getting with package installed from pypi via pip
```python
>>> import exchange_calendars
>>> exchange_calendars._version.get_versions()
{'version': '0+unknown', 'full-revisionid': None, 'dirty': None, 'error': 'unable to compute version', 'date': None}
```

I assume one of files is not in build (Manifest or smth)

**Comment by maread99** [comment]
So...
```python
>>> import exchange_calendars as xcals
>>> xcals.__version__
'0+unknown'
```

I'll look into it.

**Comment by maread99** [comment]
I tried #208 but to no avail.

I suspect the issue is simply that versioneer is not compatible with using setup.cfg to hold all the build meta (see [this versioneer issue](https://github.com/python-versioneer/python-versioneer/issues/245)).

Unless anyone can see a way to get versioneer working with the setup.cfg(?), I guess that leaves two options:

1) Revert to setup.py. This goes against the general movement in python from setup.py to setup.cfg although would allow for continuing to use versioneer.
2) Lose versioneer and hard-code the version in one place on each release, either:
    * as `__init__.__version__` and have the setup.cfg version read the attribute from there.
    * as the version defined on setup.cfg and use `import importlib.metadata` to set the value for `__init__.__version__`

If the package were one with a high-frequency of releases then I would argue for keeping versioneer, although as it is I reckon it's six of one and half a dozen of the other.

@gerrymanoim - your call obviously, I'm happy to make the necessary changes either way.

**Comment by mixilchenko** [comment]
@maread99 great research!
About first option:
I don't think there is "general movement in python from setup.py to setup.cfg" since `setup.cfg` could not be used for example when you need to build cython in your project.
Moreover, `setup.py` is more flexible since it is code.
I often see that projects have both `.py` and `.cfg` saving only static info in the latest (there is at least pandas as example)

About second option:
1. I agree with your point about current need in versioneer but it is already set up (even if it's not working rn). In future release frequency could be different and versioneer drop could be expensive.
2. Currently I use date from versioneer to validate too old releases of lib so with versioneer drop at least this feature is dropped too

Not about versioneer:
I want to say that `__version__` was rejected in PEP-396.
Most of projects have it but the accepted way to get version is `from importlib.metadata import version; print(version('exchange_calendars'))`. If we want to have PEP-396 support, I would rather use that instead of `_version.get_versions()`

**Comment by maread99** [comment]
Having dug a bit more, this is what seems to be happening...

When the package is built the correct version IS included to the metadata, i.e. the setup.cfg line `version = attr: versioneer.get_version` does resolve as required. For this reason the version is correctly identified by PyPI. It also means that the following works.
```python
>>> from importlib.metadata import version
>>> version('exchange_calendars')
'4.0.2'
```

As for what's not working... When a release is cut Versioneer should replace the contents of the _version.py file with a minimal declaration. For example, an installed 3.6.2 has a _version.py that looks like this:
```python
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-11T15:45:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1eefebe4cd576ac1a51b20d808189beb069fb07",
 "version": "3.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
```
However, since 4.0 _version.py has not been overwritten. When get_versions() is called it therefore thinks it should still try to dynamically resolve the version and (for reasons I haven't looked into) gets confused. As `__init__.__version__` calls `_version.get_versions()` the bug propagates to there.

**Comment by maread99** [comment]
#209 proposes that we move to setuptools-scm for versioning.

@mixilchenko, sorry, I suspect this isn't what you were expecting. The PR explains why it seems that setuptools-scm is the better approach. Hopefully there's an alternative way for you to achieve what you required the release dates for?

**Comment by mixilchenko** [comment]
@maread99 That is ok. I don't think I need this check at all
