### ISSUE TITLE
BUG: Futures sessions in range are all empty after 2022-05-18

### ISSUE THREAD

**Issue by MBounouar** [gerrymanoim/exchange_calendars#21]
Hi,
Dates in the future after 2022-5-18 are not considered valid days.

I also just noticed that this is a duplicate of [issue #14 ](https://github.com/gerrymanoim/exchange_calendars/issues/14)

```
import trading_calendars as tc
import exchange_calendars as ec
import pandas as pd
import datetime

tcal = tc.get_calendar("XLON")
ecal = ec.get_calendar("XLON")

print(
    tcal.sessions_in_range(
        pd.Timestamp(datetime.date(2022, 5, 1), tz="UTC"),
        pd.Timestamp(datetime.date(2022, 6, 30), tz="UTC"),
    ),
    ecal.sessions_in_range(
        pd.Timestamp(datetime.date(2022, 5, 1), tz="UTC"),
        pd.Timestamp(datetime.date(2022, 6, 30), tz="UTC"),
    ),
)
```

**Comment by gerrymanoim** [comment]
This is because of end_default here: https://github.com/gerrymanoim/exchange_calendars/blob/master/exchange_calendars/exchange_calendar.py#L40. 

You can manually create a calendar with any end date via the actual calendar class. 

A long time ago I started fixing this in https://github.com/quantopian/trading_calendars/pull/176/files (so you could pass whatever end date you wanted to `get_calendar`) but it was never merged because it might have caused incompatibilities with `zipline`. We don't need to strictly do that anymore so a similar approach should now we possible.
